version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./db:/var/lib/mysql
     restart: always
     ports:
       - "7306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: angename
       MYSQL_USER: angecoder
       MYSQL_PASSWORD: secret

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./site/core:/var/www/html
       - ./site/uploads:/var/www/uploads
       - ./conf/apache2/apache2.conf:/etc/apache2/apache2.conf
       - ./conf/apache2/alias.conf:/etc/apache2/mods-enabled/alias.conf
     ports:
       - "8981:80"
     restart: always
     domainname: gcsc.loc
     hostname: www
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: angename
       WORDPRESS_DB_USER: angecoder
       WORDPRESS_DB_PASSWORD: secret
#volumes:
